# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c7ddc140535b8a758f11afee9d22833060cc9297b063f10ae9e0352882e6e986644785d305f26219f4c0754ac4145a6df2fa16d563b427c33ef4539055e7f3e

test:
  secret_key_base: 04b2dd45e0af3b3f94a4e3b0ce9c83372ad8ed1b4bbea83678bbbd0902f75ab17b842fdf67bb14b0950d1664646ae7a4f50e056cbb8d03a46c1ce4f69b6bbd8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
